kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  namespace: development
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
